name: Java CI
on:
  - push
  - pull_request
env:
  MAVEN_OPTS: "-Xms756M -Xmx1g"
  # Here we skip the tests for quick building in the 'Build' step
  MAVEN_BUILD_PARAMS: "-DskipTests -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -Djboss.test.transformers.eap -Dci-cleanup=true -DlegacyBuild -DlegacyRelease -fae"
  MAVEN_TEST_PARAMS: "-Dmaven.test.failure.ignore=true -DfailIfNoTests=false -Dipv6 -Djboss.test.transformers.eap -Dci-cleanup=true -fae"
jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    env:
      TEST_VARIABLE: my-job-artifact
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: Build with Maven
        run: |
          mvn -B package
      - name: Zip Artifacts
        run: zip -R artifacts.zip 'surefire-reports/*.txt' 'surefire-reports/*.xml'
      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-galleon-template-raw-{{job.container.id}}
          name: ci-artifacts
          path: artifacts.zip
      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-galleon-template-raw-{{job.container.id}}
          name: ${{env.TEST_VARIABLE}}
          path: artifacts.zip

