name: Java CI
on:
  - push
  - pull_request
jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    env:
      TEST_VARIABLE: my-job-artifact
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: Build with Maven
        run: |
          mvn -B package
      - name: Zip Artifacts
        run: zip -R artifacts.zip 'surefire-reports/*.txt' 'surefire-reports/*.xml'
      - uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts.zip

